apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "nexus-pv"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pv0001