kind: Template
apiVersion: v1
metadata:
  name: backend-generator-s2i
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
      version: VERSION
    name: backend-generator
  spec:
    tags:
    - annotations: {}
      from:
        kind: DockerImage
        name: 172.30.92.36:5000/obsidian/backend-generator:latest
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
      version: VERSION
    name: backend-generator-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: backend-generator:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/obsidian-toaster/generator-backend.git
        ref: VERSION
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: fabric8/s2i-java:1.3
        env:
          - name: RELEASE
            value: VERSION
        incremental: true
    triggers:
    - github:
        secret: BCedrGCnc2IWefYxQ9sr
      type: GitHub
    - generic:
        secret: 0nqmEYlp7o6Sx_rUNIpq
      type: Generic
    - type: ConfigChange
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
      version: VERSION
    name: backend-generator
  spec:
    replicas: 1
    selector:
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 10800
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          group: org.obsidiantoaster
          project: generator
          provider: obsidian
          version: VERSION
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: AB_JOLOKIA_OFF
            value: "true"
          - name: JAVA_APP_DIR
            value: /deployments
          - name: AB_OFF
            value: "true"
          - name: JAVA_APP_JAR
            value: generator-swarm.jar
          - name: ARCHETYPE_CATALOG
            value: https://repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=public&g=org.obsidiantoaster&a=archetypes-catalog&v=VERSION&e=xml&c=archetype-catalog
          image: 172.30.92.36:5000/obsidian/backend-generator:latest
          imagePullPolicy: IfNotPresent
          name: wildfly-swarm
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - wildfly-swarm
        from:
          kind: ImageStreamTag
          name: backend-generator:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
      version: VERSION
    name: backend-generator-tls
  spec:
    ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
      version: VERSION
    name: backend-generator
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: backend-generator
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
      version: VERSION
    name: backend-generator-tls
  spec:
    tls:
      termination: passthrough
    to:
      kind: Service
      name: backend-generator-tls
      weight: 100
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: backend-generator
      group: org.obsidiantoaster
      project: generator
      provider: obsidian
      version: VERSION
    name: backend-generator
  spec:
    to:
      kind: Service
      name: backend-generator
      weight: 100
